### ISSUE TITLE
cancel 1.20 right click sign edit when clicking arm signs

### ISSUE THREAD

**Issue by matipoirierg** [alex9849/advanced-region-market#143] opened 2023-06-19 23:23 UTC
unsell region gui shift-right clicking a sign is no longer working since now on right click you open the text sign editor and the gui get cancelled.

**Comment by dandud100** [comment] 2023-06-20 07:06
What happens when the signs are in a from worldguard protected region? I think worldguard itself should prevent the signedit.

**Comment by matipoirierg** [comment] 2023-06-20 18:52
it only prevents saving the sign changes, but the editor opens anyway

**Comment by alex9849** [comment] 2023-06-21 20:14
I published an update. Please check if you still encounter that issue. I can't reproduce it anymore. I close this ticket for now. Just reopen it if the issue is still present.

**Closed by alex9849** 2023-06-21 20:14 UTC

**Comment by SenPr** [comment] 2023-06-22 00:42
I'm still getting the problem. Can you point to which commit you made the changes? I'm still trying to find the cause

**Comment by alex9849** [comment] 2023-06-22 04:30
I didn't made changes to the sign handling process. I hoped that clicks on signs don't cause exceptions anymore might solve the problem. What server version are you using? Do you use the latest version? 1.20.1 the newest build?

**Comment by Bloodlex** [comment] 2023-06-22 11:11
I also still have this problem

**Comment by Bloodlex** [comment] 2023-06-22 11:11
> I didn't made changes to the sign handling process. I hoped that clicks on signs don't cause exceptions anymore might solve the problem. What server version are you using? Do you use the latest version? 1.20.1 the newest build?

Yes, 1.20.1.
